const QUOTES = [
  {
    title: "Virtual balances",
    source: "Vest Prop Terms of Service",
    url: "https://trade.vestmarkets.com/prop-terms",
    text: "“Account” means a user’s account in the Program and other records, all as utilized by us from time-to-time to record a user’s virtual balances of digital assets and other usage of the Services.",
  },
  {
    title: "No custody of trading balances shown in the Program",
    source: "Vest Prop Terms of Service, section 6.2",
    url: "https://trade.vestmarkets.com/prop-terms",
    text: "Users do not deposit funds for trading purposes. Any balances, metrics, or performance data displayed in the Program or any given Account are for evaluation or reference purposes only and do not represent ownership of assets or trading accounts. At no time does any user control a brokerage or exchange account, have authority to execute trades, or have custody of any funds used in trading. Any performance metrics, balances, or results displayed to you are notional, simulated, or programmatic in nature and do not correspond to any real account held for your benefit.",
  },
  {
    title: "Hedging with Vest’s own capital",
    source: "Vest Prop Terms of Service",
    url: "https://trade.vestmarkets.com/prop-terms",
    text: "“Hedging Transactions” means risk-management transactions undertaken by us or our Affiliates using our own capital or balance sheet assets in order to reduce or manage the market exposure generated by virtual trading activity occurring in the Program.",
  },
  {
    title: "Evaluation phase uses simulated capital",
    source: "Vest docs, Vest Capital overview",
    url: "https://docs.vestmarkets.com/vest-capital/overview",
    text: "With Evaluation — The traditional prop path. Purchase an account, trade simulated capital in the Evaluation Phase, and configure your risk and reward; Profit Target, Daily Loss Limit, and profit split. Hit your goal to go Live.",
  },
  {
    title: "Live Funded Account, as described by Vest",
    source: "Vest docs, Vest Capital overview",
    url: "https://docs.vestmarkets.com/vest-capital/overview",
    text: "Real Vest capital. Not simulated, actual platform capital backing your positions.",
  },
  {
    title: "Claim Profit",
    source: "Vest docs, Claiming Profit",
    url: "https://docs.vestmarkets.com/vest-capital/claiming-profit",
    text: "Claim Profit moves profit from a Live Funded Account to your Primary Account. It’s the first of two steps if you want to move funds all the way out to an external wallet.",
  },
  {
    title: "Claim Profit is not a withdrawal",
    source: "Vest docs, Claiming Profit",
    url: "https://docs.vestmarkets.com/vest-capital/claiming-profit",
    text: "Claim Profit is not the same as a Withdrawal. Claim Profit moves funds from a Funded Account to your Primary Account. Withdrawal moves funds from your Primary Account to an external wallet.",
  },
  {
    title: "Withdrawal",
    source: "Vest docs, Withdrawals",
    url: "https://docs.vestmarkets.com/platform/withdrawals",
    text: "Withdrawals move USDC from your Primary Account to an external wallet address.",
  },
  {
    title: "Withdrawal limits",
    source: "Vest docs, Withdrawals",
    url: "https://docs.vestmarkets.com/platform/withdrawals",
    text: "Minimum withdrawal: 1 USDC. $50,000 rolling 24-hour limit. Withdrawals process instantly until your rolling 24-hour total reaches $50,000. Any withdrawal that pushes your rolling total over that amount is subject to a 24-hour processing period.",
  },
  {
    title: "Marketing site",
    source: "vestmarkets.com",
    url: "https://vestmarkets.com",
    text: "Trade on a simulated account. Hit the 10% profit target while respecting risk rules. Get funded and keep 80% of every dollar you make. Withdrawals hit your wallet immediately.",
  },
  {
    title: "Card payments",
    source: "Vest Privacy Policy",
    url: "https://docs.vestmarkets.com/resources/terms-and-privacy-policies/privacy-policy",
    text: "When you pay through Stripe Checkout, Stripe processes your payment details. If you opt to save a method, Stripe stores it for later Vest Checkout sessions. We may receive Stripe identifiers and limited card details, such as card brand, last four digits, and expiry, but not the full card number or CVC/CVV.",
  },
];

const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 });
const num = new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 });
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const TOPUP_KINDS = new Set([
  "coinbase_prime_to_safe",
  "coinbase_hot_to_contract",
  "safe_to_contract",
  "safe_to_lifi",
  "bridge_to_contract",
  "inferred_lifi_to_contract",
]);
const PALETTE = {
  "Treasury Safe": "#7eb6d9",
  "Second Safe": "#6e8cae",
  Base: "#8fbfa8",
  Arbitrum: "#c4b4e0",
  Ethereum: "#e0c07a",
  "Older contracts": "#8d99a6",
  "Other chains": "#d7c4a3",
  "Coinbase Prime": "#7eb6d9",
  Coinbase: "#9dccb4",
  "Payout contracts": "#e0c07a",
  Recipients: "#c4b4e0",
  "Custody (inferred)": "#d7a56a",
};
const TEXT = "#e8eef4";
const MUTED = "#9aa6b4";
const GRID = "rgba(232,238,244,0.08)";

function esc(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

function fmtTime(iso, zone) {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: zone,
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(d);
}

function shortDate(iso) {
  if (!iso) return "—";
  const [y, m, d] = iso.slice(0, 10).split("-").map(Number);
  if (!y || !m || !d) return iso.slice(0, 10);
  return `${d} ${MONTHS[m - 1]}`;
}

function compactUsd(n) {
  if (n === null || n === undefined || Number.isNaN(Number(n))) return "—";
  const value = Number(n);
  const sign = value < 0 ? "-" : "";
  const abs = Math.abs(value);
  if (abs >= 1000000) {
    const scaled = abs / 1000000;
    const digits = scaled >= 10 ? 1 : 2;
    return `${sign}$${scaled.toFixed(digits).replace(/\.0+$/, "").replace(/(\.\d)0$/, "$1")}m`;
  }
  if (abs >= 10000) return `${sign}$${Math.round(abs / 1000)}k`;
  return usd.format(value);
}

function delta(v) {
  if (v === null || v === undefined || Number.isNaN(Number(v))) return "<span class='muted'>—</span>";
  const cls = v > 0 ? "up" : v < 0 ? "down" : "";
  const sign = v > 0 ? "+" : "";
  return `<span class="${cls}">${sign}${usd.format(v)}</span>`;
}

function short(addr) {
  if (!addr) return "—";
  return `${addr.slice(0, 6)}…${addr.slice(-4)}`;
}

function badge(attr) {
  const cls = attr === "inferred" ? "inferred" : attr === "contract source" ? "source" : "";
  return `<span class="badge ${cls}">${esc(attr || "—")}</span>`;
}

function plainName(w) {
  const names = {
    treasury_safe_eth: "Treasury Safe",
    treasury_safe_base: "Treasury Safe on Base",
    treasury_safe_arb: "Treasury Safe on Arbitrum",
    safe2_eth: "Second Safe",
    base_contract: "Base payout contract",
    arb_contract: "Arbitrum payout contract",
    eth_deposit: "Ethereum payout contract",
    op_deposit: "Optimism, same address",
    polygon_deposit: "Polygon, same address",
    base_e80f: "Base, same address as Ethereum",
    bsc_contract: "BNB payout contract",
    arb_old: "Older Arbitrum contract",
    base_old: "Older Base contract",
    bsc_old: "Older BNB contract",
  };
  return names[w.id] || w.role;
}

function leadSentence(latest, charts) {
  const totals = latest.totals || {};
  let change = "";
  if (typeof totals.change_24h === "number") {
    if (totals.change_24h < 0) change = `, down ${compactUsd(Math.abs(totals.change_24h))} in 24h`;
    else if (totals.change_24h > 0) change = `, up ${compactUsd(totals.change_24h)} in 24h`;
    else change = ", unchanged in 24h";
  }
  const payouts = charts?.payouts_24h;
  let payout = "payout counts for the last 24h are not in this snapshot";
  if (payouts) {
    if (payouts.count === 0) payout = "no payouts went out";
    else if (payouts.count === 1) payout = "1 payout went out";
    else payout = `${num.format(payouts.count)} payouts went out`;
  }
  const last = charts?.last_topup?.t;
  const snap = (latest.generated_at || "").slice(0, 10);
  let top = "no treasury top-up is in the stored list";
  if (last) {
    top = last.slice(0, 10) === snap
      ? "a treasury top-up was recorded on the snapshot day"
      : `no treasury top-up since ${shortDate(last)}`;
  }
  const first = payout.charAt(0).toUpperCase() + payout.slice(1);
  return `Tracked wallets hold ${compactUsd(totals.usdc || 0)}${change}. ${first}; ${top}.`;
}

function daysSince(latest, charts) {
  const last = charts?.last_topup?.t;
  const snap = latest.generated_at;
  if (!last || !snap) return { value: "—", sub: "No top-up in the stored list" };
  const days = Math.round((Date.parse(`${snap.slice(0, 10)}T00:00:00Z`) - Date.parse(`${last.slice(0, 10)}T00:00:00Z`)) / 86400000);
  return {
    value: String(Math.max(0, days)),
    sub: `Last one ${shortDate(last)} ${last.slice(11, 16)} UTC`,
  };
}

function runwayText(total, pace) {
  if (!pace || pace <= 0 || total === null || total === undefined) {
    return "Illustrative estimate, not a prediction. The last 7 days of payouts do not give a pace to divide into, so no day-count is shown. Custody and exchange balances are not included.";
  }
  const days = Number(total) / pace;
  const shown = days >= 10 ? String(Math.round(days)) : String(Math.round(days * 10) / 10);
  return `Illustrative estimate, not a prediction. At the last 7 days’ payout pace (${compactUsd(pace)} a day), the ${compactUsd(total)} tracked here would cover about ${shown} days. Custody and exchange balances are not included.`;
}

async function loadJson(path) {
  const res = await fetch(`${path}?t=${Date.now()}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`${path} ${res.status}`);
  return res.json();
}

function tip() {
  return {
    backgroundColor: "#1c2530",
    borderColor: "rgba(232,238,244,0.12)",
    textStyle: { color: TEXT, fontFamily: "Outfit, sans-serif" },
    confine: true,
  };
}

function axisCommon() {
  return {
    axisLabel: { color: MUTED, fontSize: 11 },
    axisLine: { lineStyle: { color: GRID } },
    splitLine: { lineStyle: { color: GRID } },
  };
}

function moneyTip(params) {
  const rows = Array.isArray(params) ? params : [params];
  const head = esc(rows[0]?.axisValue ?? rows[0]?.name ?? "");
  const lines = rows.filter((row) => row.value !== null && row.value !== undefined && row.seriesName !== "Top-up").map((row) => {
    const raw = Array.isArray(row.value) ? row.value[1] : row.value;
    const shown = row.seriesName === "Payouts" ? Math.abs(raw) : raw;
    return `${row.marker} ${esc(row.seriesName)}: ${usd.format(shown)}`;
  });
  return [head, ...lines].join("<br>");
}

function windowStart(dates, days) {
  if (!dates.length || days === "all") return dates[0];
  const end = dates[dates.length - 1];
  const cut = new Date(Date.parse(`${end}T00:00:00Z`) - (Number(days) - 1) * 86400000).toISOString().slice(0, 10);
  return dates.find((date) => date >= cut) || dates[0];
}

function balanceNote(days) {
  const range = days === "all"
    ? "Showing the full reconstructed history, which is often flat before the recent moves."
    : `Showing the last ${days} days.`;
  return `Each band is a group of wallets. Diamonds mark days with a top-up in the stored flow list. ${range} The bands are the seven wallets with daily history, so this stack is a little smaller than the headline total.`;
}

function balanceOption(history, flows, days) {
  const daily = history.daily || {};
  const maps = {};
  const dates = new Set();
  Object.entries(daily).forEach(([key, rows]) => {
    maps[key] = new Map((rows || []).map(([date, value]) => [date, value]));
    (rows || []).forEach(([date]) => dates.add(date));
  });
  const start = windowStart([...dates].sort(), days);
  const ordered = [...dates].filter((date) => date >= start).sort();
  const groups = [
    ["Treasury Safe", ["treasury_safe_eth"]],
    ["Second Safe", ["safe2_eth"]],
    ["Base", ["base_contract"]],
    ["Arbitrum", ["arb_contract"]],
    ["Ethereum", ["eth_deposit"]],
    ["Older contracts", ["arb_old", "bsc_old"]],
  ];
  const stacked = groups.map(([name, keys]) => ({
    name,
    type: "line",
    stack: "balance",
    smooth: 0.2,
    showSymbol: false,
    areaStyle: { color: PALETTE[name], opacity: 0.92 },
    lineStyle: { width: 1.25, color: PALETTE[name] },
    itemStyle: { color: PALETTE[name] },
    emphasis: { focus: "series" },
    data: ordered.map((date) => {
      let sum = 0;
      let any = false;
      keys.forEach((key) => {
        const value = maps[key]?.get(date);
        if (value === null || value === undefined) return;
        any = true;
        sum += Number(value);
      });
      return any ? Math.round(sum * 100) / 100 : null;
    }),
  }));
  const topups = new Map();
  (flows.topups || []).forEach((row) => {
    if (!TOPUP_KINDS.has(row.kind)) return;
    const day = row.t.slice(0, 10);
    const slot = topups.get(day) || { count: 0 };
    slot.count += 1;
    topups.set(day, slot);
  });
  const marks = ordered.map((date, index) => {
    if (!topups.has(date)) return null;
    const total = stacked.reduce((sum, series) => sum + (series.data[index] || 0), 0);
    return total > 0 ? total : null;
  });
  stacked.push({
    name: "Top-up",
    type: "scatter",
    symbol: "diamond",
    symbolSize: 12,
    itemStyle: { color: "#f4f7fa", borderColor: "#e0c07a", borderWidth: 1.5 },
    data: marks,
    z: 6,
    tooltip: { show: false },
  });
  return {
    color: groups.map(([name]) => PALETTE[name]),
    tooltip: {
      ...tip(),
      trigger: "axis",
      formatter(params) {
        const rows = Array.isArray(params) ? params : [params];
        const date = rows[0]?.axisValue || "";
        let total = 0;
        const lines = [`<strong>${esc(date)}</strong>`];
        rows.forEach((row) => {
          if (row.seriesName === "Top-up" || row.value === null || row.value === undefined) return;
          total += Number(row.value);
          lines.push(`${row.marker} ${esc(row.seriesName)}: ${usd.format(row.value)}`);
        });
        lines.push(`<strong>These bands: ${usd.format(total)}</strong>`);
        const mark = topups.get(date);
        if (mark) lines.push(`${mark.count} top-up transfer${mark.count === 1 ? "" : "s"} recorded this day`);
        return lines.join("<br>");
      },
    },
    legend: { top: 0, textStyle: { color: MUTED }, type: "scroll" },
    grid: { left: 8, right: 12, top: 42, bottom: 28, containLabel: true },
    xAxis: { type: "category", data: ordered, ...axisCommon(), axisLabel: { color: MUTED, fontSize: 11, hideOverlap: true } },
    yAxis: { type: "value", min: 0, ...axisCommon(), axisLabel: { color: MUTED, fontSize: 11, formatter: (v) => compactUsd(v) } },
    series: stacked,
  };
}

function flowOption(charts) {
  const rows = charts?.daily_flows || [];
  return {
    tooltip: { ...tip(), trigger: "axis", formatter: moneyTip },
    legend: { top: 0, textStyle: { color: MUTED } },
    grid: { left: 8, right: 12, top: 42, bottom: 28, containLabel: true },
    xAxis: { type: "category", data: rows.map((row) => row.date.slice(5)), ...axisCommon(), axisLabel: { color: MUTED, fontSize: 11, hideOverlap: true } },
    yAxis: { type: "value", ...axisCommon(), axisLabel: { color: MUTED, fontSize: 11, formatter: (v) => compactUsd(v) } },
    series: [
      { name: "Top-ups", type: "bar", stack: "in", barGap: "-100%", itemStyle: { color: "#7eb6d9" }, data: rows.map((row) => row.topups) },
      { name: "Deposits", type: "bar", stack: "in", itemStyle: { color: "#8fbfa8" }, data: rows.map((row) => row.deposits) },
      { name: "Payouts", type: "bar", stack: "out", barGap: "-100%", itemStyle: { color: "#d7a0a0" }, data: rows.map((row) => -row.payouts) },
      { name: "Net", type: "line", showSymbol: false, z: 4, itemStyle: { color: "#f4f7fa" }, lineStyle: { width: 2 }, data: rows.map((row) => row.net) },
    ],
  };
}

function donutOption(latest) {
  const groups = new Map();
  (latest.wallets || []).forEach((wallet) => {
    let name = "Other chains";
    if (wallet.id.startsWith("treasury_safe")) name = "Treasury Safe";
    else if (wallet.id === "safe2_eth") name = "Second Safe";
    else if (wallet.id === "base_contract") name = "Base";
    else if (wallet.id === "arb_contract") name = "Arbitrum";
    else if (wallet.id === "eth_deposit") name = "Ethereum";
    else if (["arb_old", "base_old", "bsc_old"].includes(wallet.id)) name = "Older contracts";
    groups.set(name, (groups.get(name) || 0) + (Number(wallet.usdc) || 0));
  });
  const data = [...groups.entries()]
    .filter(([, value]) => value > 0.5)
    .map(([name, value]) => ({ name, value: Math.round(value * 100) / 100, itemStyle: { color: PALETTE[name] || "#8d99a6" } }));
  return {
    tooltip: { ...tip(), trigger: "item", formatter: (row) => `${esc(row.name)}<br>${usd.format(row.value)} · ${row.percent}%` },
    legend: { bottom: 0, textStyle: { color: MUTED }, type: "scroll" },
    series: [{
      type: "pie",
      radius: ["46%", "68%"],
      center: ["50%", "44%"],
      avoidLabelOverlap: true,
      label: { color: TEXT, fontSize: 11, formatter: (row) => (row.percent >= 5 ? `${row.name}\n${compactUsd(row.value)}` : "") },
      data,
    }],
  };
}

function bucketOption(charts) {
  const rows = charts?.payout_buckets || [];
  return {
    tooltip: {
      ...tip(),
      trigger: "axis",
      formatter(params) {
        const row = (Array.isArray(params) ? params : [params])[0];
        const source = rows[row.dataIndex] || {};
        return `${esc(row.axisValue)}<br>${num.format(source.count || 0)} payouts<br>${usd.format(source.volume || 0)}`;
      },
    },
    grid: { left: 8, right: 8, top: 16, bottom: 8, containLabel: true },
    xAxis: {
      type: "category",
      data: rows.map((row) => row.label.replace("Under $100", "< $100").replace("Over $20k", "> $20k")),
      ...axisCommon(),
      axisLabel: { color: MUTED, fontSize: 11, interval: 0 },
    },
    yAxis: { type: "value", ...axisCommon(), name: "Payouts", nameTextStyle: { color: MUTED } },
    series: [{ type: "bar", data: rows.map((row) => row.count), itemStyle: { color: "#c4b4e0", borderRadius: [6, 6, 0, 0] } }],
  };
}

function countOption(charts) {
  const rows = charts?.daily_flows || [];
  return {
    tooltip: { ...tip(), trigger: "axis", formatter: (params) => `${esc(params[0].axisValue)}<br>${num.format(params[0].value)} payouts` },
    grid: { left: 8, right: 8, top: 16, bottom: 8, containLabel: true },
    xAxis: { type: "category", data: rows.map((row) => row.date.slice(5)), ...axisCommon(), axisLabel: { color: MUTED, fontSize: 11, hideOverlap: true } },
    yAxis: { type: "value", ...axisCommon() },
    series: [{ type: "bar", data: rows.map((row) => row.payout_count), itemStyle: { color: "#8fbfa8", borderRadius: [4, 4, 0, 0] } }],
  };
}

function sankeyDepths(links) {
  const incoming = {};
  links.forEach((link) => {
    incoming[link.source] = incoming[link.source] || [];
    incoming[link.target] = incoming[link.target] || [];
    incoming[link.target].push(link.source);
  });
  const memo = {};
  function depth(name) {
    if (memo[name] !== undefined) return memo[name];
    const sources = incoming[name] || [];
    memo[name] = 0;
    memo[name] = sources.length ? 1 + Math.max(...sources.map(depth)) : 0;
    return memo[name];
  }
  Object.keys(incoming).forEach(depth);
  return memo;
}

function sankeyNodes(links, width, vertical) {
  const depthOf = sankeyDepths(links);
  const outgoing = {};
  const incoming = {};
  const names = [];
  links.forEach((link) => {
    outgoing[link.source] = (outgoing[link.source] || 0) + Number(link.value);
    incoming[link.target] = (incoming[link.target] || 0) + Number(link.value);
    if (!names.includes(link.source)) names.push(link.source);
    if (!names.includes(link.target)) names.push(link.target);
  });
  const levelSum = {};
  names.forEach((name) => {
    const amount = outgoing[name] || incoming[name] || 0;
    levelSum[depthOf[name]] = (levelSum[depthOf[name]] || 0) + amount;
  });
  const gutter = vertical ? 148 : 168;
  const plot = Math.max(160, width - gutter - 16);
  return names.map((name) => {
    const amount = outgoing[name] || incoming[name] || 0;
    const share = levelSum[depthOf[name]] ? amount / levelSum[depthOf[name]] : 1;
    const wideEnough = !vertical || share * plot >= 156;
    const inside = vertical && wideEnough;
    return {
      name,
      itemStyle: { color: PALETTE[name] || "#8d99a6" },
      label: {
        position: inside ? "inside" : "right",
        color: inside ? "#10141a" : TEXT,
        fontSize: width < 420 ? 11 : 12,
        fontWeight: 600,
        fontFamily: "Outfit, sans-serif",
        lineHeight: 15,
        width: inside ? Math.max(88, Math.floor(share * plot - 16)) : (vertical ? 128 : 146),
        overflow: "break",
        textBorderColor: inside ? "transparent" : "#161c24",
        textBorderWidth: inside ? 0 : 3,
        formatter: () => `${name}\n${compactUsd(amount)}`,
      },
    };
  });
}

function sankeyHeight(width) {
  return width < 760 ? 640 : 500;
}

function chartBoxWidth(el) {
  const card = el.closest(".card") || el.parentElement;
  if (!card) return el.clientWidth;
  const style = getComputedStyle(card);
  const pad = (parseFloat(style.paddingLeft) || 0) + (parseFloat(style.paddingRight) || 0);
  return Math.max(280, Math.floor(card.clientWidth - pad));
}

function sankeyOption(charts, width) {
  const links = charts?.sankey?.links || [];
  const vertical = width < 760;
  const gutter = vertical ? 148 : 168;
  return {
    tooltip: {
      ...tip(),
      trigger: "item",
      formatter: (row) => (row.dataType === "edge"
        ? `${esc(row.data.source)} → ${esc(row.data.target)}<br>${usd.format(row.data.value)}`
        : `${esc(row.name)}<br>${usd.format(row.value)}`),
    },
    series: [{
      type: "sankey",
      orient: vertical ? "vertical" : "horizontal",
      data: sankeyNodes(links, width, vertical),
      links,
      nodeAlign: "justify",
      nodeWidth: vertical ? 48 : 16,
      nodeGap: vertical ? 18 : 26,
      left: 8,
      right: gutter,
      top: 12,
      bottom: vertical ? 16 : 36,
      draggable: false,
      animation: false,
      layoutIterations: 32,
      lineStyle: { color: "gradient", curveness: 0.45, opacity: 0.32 },
      emphasis: { focus: "adjacency" },
    }],
  };
}

function drawCharts(latest, history, flows) {
  const charts = flows.charts || {};
  const mount = (id, option) => {
    const el = document.getElementById(id);
    if (!el || !window.echarts) return null;
    const chart = window.echarts.init(el, null, { renderer: "canvas" });
    chart.setOption(option);
    return chart;
  };
  const sankeyEl = document.getElementById("chart-sankey");
  let sankeyWidth = sankeyEl ? chartBoxWidth(sankeyEl) : 0;
  if (sankeyEl && sankeyWidth) sankeyEl.style.height = `${sankeyHeight(sankeyWidth)}px`;
  const balanceChart = mount("chart-balance", balanceOption(history, flows, 14));
  const sankeyChart = mount("chart-sankey", sankeyOption(charts, sankeyWidth || 800));
  const live = [
    balanceChart,
    mount("chart-flow", flowOption(charts)),
    mount("chart-donut", donutOption(latest)),
    mount("chart-buckets", bucketOption(charts)),
    mount("chart-counts", countOption(charts)),
    sankeyChart,
  ].filter(Boolean);
  let frame = 0;
  const refit = () => {
    cancelAnimationFrame(frame);
    frame = requestAnimationFrame(() => {
      const el = document.getElementById("chart-sankey");
      if (!el || !sankeyChart) return;
      const width = chartBoxWidth(el);
      const height = sankeyHeight(width);
      el.style.height = `${height}px`;
      sankeyChart.resize({ width, height });
      live.forEach((chart) => {
        if (chart !== sankeyChart) chart.resize();
      });
      if (Math.abs(width - sankeyWidth) < 2) return;
      sankeyWidth = width;
      sankeyChart.setOption(sankeyOption(charts, width), { notMerge: true });
      sankeyChart.resize({ width, height });
    });
  };
  window.addEventListener("resize", refit);
  if (window.ResizeObserver && sankeyEl) {
    const observer = new ResizeObserver(refit);
    observer.observe(sankeyEl.parentElement || sankeyEl);
  }
  const range = document.getElementById("balance-range");
  const note = document.getElementById("balance-note");
  range?.addEventListener("click", (event) => {
    const button = event.target.closest("button");
    if (!button || !balanceChart) return;
    const days = button.dataset.days === "all" ? "all" : Number(button.dataset.days);
    range.querySelectorAll("button").forEach((el) => {
      const on = el === button;
      el.classList.toggle("active", on);
      el.setAttribute("aria-pressed", on ? "true" : "false");
    });
    if (note) note.textContent = balanceNote(days);
    balanceChart.setOption(balanceOption(history, flows, days), true);
  });
}

function whenChartsReady(fn) {
  if (window.echarts) {
    fn();
    return;
  }
  const script = document.createElement("script");
  script.src = "https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js";
  script.onload = fn;
  script.onerror = () => {
    const note = document.getElementById("chart-status");
    if (note) note.textContent = "The chart library did not load. The summary and the tables further down still use the snapshot.";
  };
  document.head.appendChild(script);
}

function zksyncBlurb(z) {
  if (!z || (z.error && !z.tx)) return "The zkSync router check did not return a transaction this run.";
  const stale = z.stale ? " This copy was kept from the previous run because the explorer request failed." : "";
  return `The address returned by <span class="mono">router()</span> is <span class="mono">${esc(z.address)}</span>. The newest transaction on page 1 of the zkSync Era block explorer API (newest first) is <a href="${esc(z.explorer)}">${esc(z.tx)}</a>, received at ${esc(fmtTime(z.received_at, "UTC"))} UTC (${esc(fmtTime(z.received_at, "Europe/Madrid"))} Europe/Madrid), status ${esc(z.status || "—")}. Source: ${esc(z.source || "")}.${esc(stale)}`;
}

function payoutTable(flows) {
  const entries = Object.entries(flows.withdrawals || {});
  if (!entries.length) return "<p class='note'>No payout aggregates stored yet.</p>";
  return `<div class="scroll"><table>
    <thead><tr><th>Contract</th><th class="num">Count</th><th class="num">Volume</th><th class="num">Median</th><th class="num">Largest</th><th class="num">Recipients</th></tr></thead>
    <tbody>${entries.map(([id, row]) => {
      const window = row.windows?.["30"] || {};
      return `<tr>
        <td>${esc(plainName({ id, role: id }))}</td>
        <td class="num">${num.format(window.count || 0)}</td>
        <td class="num">${usd.format(window.volume || 0)}</td>
        <td class="num">${window.median === null || window.median === undefined ? "—" : usd.format(window.median)}</td>
        <td class="num">${window.max === null || window.max === undefined ? "—" : usd.format(window.max)}</td>
        <td class="num">${num.format(window.unique_recipients || 0)}</td>
      </tr>`;
    }).join("")}</tbody>
  </table></div>
  <p class="note">Last 30 days of stored withdraw transfers for the contracts included in this aggregate. Median is the middle amount, or the mean of the two middle amounts when the count is even.</p>`;
}

function methodology(latest, flows) {
  const coverage = flows.coverage || {};
  const incomplete = Object.entries(coverage).filter(([, meta]) => meta && meta.reached_cutoff === false && !meta.skipped);
  return `
    <h3>How the numbers are computed</h3>
    <ul>
      <li><strong>Balance.</strong> An RPC <span class="mono">balanceOf</span> call on the USDC contract, divided by 10^decimals. Blockscout’s <span class="mono">/token-balances</span> endpoint can lag that read. On 4 Oct 2026 it still showed $378.7k for the Base contract <span class="mono">0x55133c825603E6A5b9E911ABAb23e75Dc3Bb07aF</span> when the live balance was $216.9k.</li>
      <li><strong>Payout float, an inference.</strong> The on-chain wallets appear to act as a payout float topped up in batches from Coinbase and Coinbase Prime. Custody and exchange balances are not visible on-chain, so the tracked total is not total firm reserves.</li>
      <li><strong>Top-up.</strong> USDC arriving at a payout contract from the Treasury Safe, Coinbase, Coinbase Prime, LI.FI, a mint, or a bridge, including an inferred LI.FI completion. A day is also marked when Coinbase Prime funds the Treasury Safe, or when the Safe sends USDC to LI.FI or straight to a contract. Transfers between monitored wallets are not counted twice.</li>
      <li><strong>Deposit.</strong> Other USDC arriving at a payout contract from an address that is not one of the monitored wallets.</li>
      <li><strong>Payout.</strong> USDC leaving a current or older payout contract in a transaction whose method is <span class="mono">withdraw</span> or selector <span class="mono">0xbd69a7ae</span>, to an address outside the monitored set.</li>
      <li><strong>Moved to custody (inferred).</strong> Treasury Safe USDC sent to <span class="mono">0x18F0Ddbab74A4BF7f4EF5c5469334CAc0DdC5b77</span> (Coinbase Prime deposit forwarder, inferred), or directly to Coinbase or Coinbase Prime. These are not payouts. The forwarder is not a tracked balance.</li>
      <li><strong>Recipients</strong> on the flow diagram are the outside addresses on those withdraw transfers. The chain does not name them.</li>
      <li>The headline total adds every wallet in the table, including a stale previous balance when a new read fails. The 24h change sums the core wallets only when each of them has an earlier point. A missing point is left blank, not treated as zero.</li>
      <li>The balance chart uses daily reconstructed history for the seven seed wallets. It opens on the last 14 days; 30 days and the full history are on the toggle. Older Arbitrum history starts on 27 Sep 2026, and older BSC history starts on 3 Oct 2026. Days before that are missing history, not a recorded zero. Optimism, Polygon, and the small remainder are in the donut and the total, not in the stacked bands.</li>
      <li>RPCs are public endpoints, tried in order with retries. A failed read keeps the previous stored balance. Transfers on Ethereum, Base, Arbitrum, Optimism, and Polygon come from Blockscout. BSC uses <span class="mono">eth_getLogs</span> because the BSC Blockscout hosts tried here returned 404. BSC timestamps inside a log chunk are estimated from the chunk’s end block.</li>
      <li>Daily backfill, when the transfer scan reached 90 days and the balance read succeeded, is the current balance minus later USDC transfers. It stops where an earlier day would imply a negative balance.</li>
    </ul>
    ${incomplete.length ? `<p class="note">Transfer history has not yet reached the 90-day cutoff for: ${incomplete.map(([id]) => esc(id)).join(", ")}. Those figures cover the transfers stored so far.</p>` : `<p class="note">Transfer scans that report reached_cutoff include transfers back to the lookback window.</p>`}
    <p class="note">Machine-readable files: <a href="data/latest.json">data/latest.json</a>, <a href="data/history.json">data/history.json</a>, <a href="data/flows.json">data/flows.json</a>. Raw: <span class="mono">https://raw.githubusercontent.com/diatle-glitch/vest-watch/main/data/latest.json</span></p>
    <h3>Addresses</h3>
    <div class="scroll"><table>
      <thead><tr><th>What it is</th><th>Chain</th><th>Address</th><th>Attribution</th><th>Source note</th></tr></thead>
      <tbody>
        ${(latest.wallets || []).map((w) => `<tr>
          <td>${esc(plainName(w))}</td><td>${esc(w.chain)}</td>
          <td class="mono"><a href="${esc(w.explorer)}">${esc(w.address)}</a></td>
          <td>${badge(w.attribution)}</td>
          <td>${esc(w.note)}</td>
        </tr>`).join("")}
        ${(flows.counterparties || []).map((c) => `<tr>
          <td>${esc(c.label)}</td><td></td>
          <td class="mono">${esc(c.address || "—")}</td>
          <td>${badge("reference")}</td>
          <td>${esc(c.basis)}</td>
        </tr>`).join("")}
      </tbody>
    </table></div>
    <h3>Withdrawals on the SrcBridge contracts</h3>
    <p>The Ethereum address <span class="mono">0xE80F92077131b9890599E418AE323de71cE1C35a</span> is a TransparentUpgradeableProxy. Blockscout lists its implementation as <a href="https://eth.blockscout.com/address/0xEcD91C77B98d507E3C20Bac86D2541ECbDc881E3">0xEcD91C77B98d507E3C20Bac86D2541ECbDc881E3</a>, verified source name SrcBridge. That source contains <span class="mono">string public constant NAME = "VestRouterV2"</span> and <span class="mono">bytes32 public constant BRIDGE_OPERATOR_ROLE = keccak256("BRIDGE_OPERATOR_ROLE")</span>.</p>
    <p>The verified <span class="mono">withdraw</span> function calls <span class="mono">_withdraw</span>. That function requires the caller, or an address recovered from <span class="mono">validatorSignature</span>, to have <span class="mono">BRIDGE_OPERATOR_ROLE</span>. It also checks chain id, a supported token, a replay mapping <span class="mono">completedTransactions</span>, and a request signature when the account is not <span class="mono">msg.sender</span>. The parameter named <span class="mono">signatureProof</span> is passed to a signer-delegation check. The verified source has no balance variable and no Merkle or state-root check of an off-chain account. Source reviewed from Blockscout on 2026-10-04.</p>
    <ul>
      ${((flows.onchain || {}).checks || []).map((c) => `<li>${esc(c.chain)} ${esc(short(c.address))}: ${c.error ? `read failed (${esc(c.error)})` : (c.has_bridge_operator_role ? "operator has BRIDGE_OPERATOR_ROLE" : "operator does not have BRIDGE_OPERATOR_ROLE on this call")}</li>`).join("")}
    </ul>
    <p class="note"><span class="mono">router()</span> on the Ethereum proxy returned <span class="mono">${esc(flows.onchain?.router?.address || "—")}</span>.</p>
    <h3>Evaluation fees and the legacy zkSync router</h3>
    <p>Vest’s privacy policy says purchases are processed through Stripe Checkout (quote below). Those card payments are off-chain. They are not part of the USDC totals on this page.</p>
    <p>${zksyncBlurb(flows.zksync_router)}</p>
    <h3>Vest’s published terms</h3>
    <p class="note">Quotes below are copied from the listed pages. Pages were fetched on 2026-10-04.</p>
    ${QUOTES.map((q) => `<h3>${esc(q.title)}</h3><blockquote><p>${esc(q.text)}</p></blockquote><p class="note"><a href="${esc(q.url)}">${esc(q.source)}</a></p>`).join("")}
  `;
}

function render(latest, history, flows) {
  const totals = latest.totals || {};
  const charts = flows.charts || {};
  const since = daysSince(latest, charts);
  const payouts = charts.payouts_24h || {};
  const rows = charts.daily_flows || [];
  const summed = rows.reduce((acc, row) => {
    acc.topups += row.topups;
    acc.deposits += row.deposits;
    acc.payouts += row.payouts;
    return acc;
  }, { topups: 0, deposits: 0, payouts: 0 });
  const partial = (flows.flow_summary?.["30"]?.partial_wallets || []).join(", ");
  document.getElementById("updated").textContent = `${fmtTime(latest.generated_at, "UTC")} UTC · ${fmtTime(latest.generated_at, "Europe/Madrid")} Madrid`;
  document.getElementById("app").innerHTML = `
    <p class="lede">${esc(leadSentence(latest, charts))}</p>
    <section class="kpis" aria-label="Key figures">
      <article class="kpi"><p class="k">Balance now</p><p class="v">${usd.format(totals.usdc || 0)}</p><p class="s">${totals.partial ? "One read failed; an older balance was kept" : "USDC in the monitored wallets"}</p></article>
      <article class="kpi"><p class="k">Change, 24h</p><p class="v">${delta(totals.change_24h)}</p><p class="s">Core wallets with an earlier point</p></article>
      <article class="kpi"><p class="k">Payouts out, 24h</p><p class="v">${payouts.volume === undefined ? "—" : usd.format(payouts.volume)}</p><p class="s">${payouts.count === undefined ? "Not in this snapshot" : `${num.format(payouts.count)} withdraw transfers`}</p></article>
      <article class="kpi"><p class="k">Days since last top-up</p><p class="v">${esc(since.value)}</p><p class="s">${esc(since.sub)}</p></article>
    </section>
    <aside class="runway"><strong>Runway at the current payout pace.</strong> ${esc(runwayText(totals.usdc, charts.pace_7d?.per_day))}</aside>
    <div class="glossary">
      <p><strong>Top-up.</strong> USDC sent in from Coinbase, Coinbase Prime, the treasury Safe, or a bridge to refill a payout contract.</p>
      <p><strong>Payout contract.</strong> A monitored contract that sends USDC out with the withdraw method.</p>
      <p><strong>Deposit.</strong> Other USDC sent into a payout contract from outside the monitored wallets.</p>
      <p><strong>Tracked total.</strong> On-chain USDC in these wallets. It is not exchange custody, and it is not a virtual balance in Vest’s program.</p>
    </div>
    <p class="note" id="chart-status"></p>
    <div class="charts">
      <div class="chart-grid hero-charts">
        <section class="card" id="balances">
          <div class="chart-head">
            <div>
              <h2>Where the balance has been</h2>
              <p class="note" id="balance-note">${esc(balanceNote(14))}</p>
            </div>
            <div class="tabs" id="balance-range" role="group" aria-label="Balance chart range">
              <button type="button" data-days="14" class="active" aria-pressed="true">14d</button>
              <button type="button" data-days="30" aria-pressed="false">30d</button>
              <button type="button" data-days="all" aria-pressed="false">All</button>
            </div>
          </div>
          <div id="chart-balance" class="chart"></div>
        </section>
        <section class="card" id="where">
          <h2>Where the money sits now</h2>
          <p class="note">Share of the tracked USDC total. Slices under about $1 are omitted from the ring.</p>
          <div id="chart-donut" class="chart"></div>
        </section>
      </div>
      <section class="card" id="inout">
        <h2>Money in and money out</h2>
        <p class="note">Last 30 days. Top-ups and deposits sit above zero. Payouts sit below. The line is that day’s net. Over the window: top-ups ${usd.format(summed.topups)}, deposits ${usd.format(summed.deposits)}, payouts ${usd.format(summed.payouts)}.</p>
        ${partial ? `<p class="note">The transfer scan does not yet cover this whole window for ${esc(partial)}.</p>` : ""}
        <div id="chart-flow" class="chart"></div>
      </section>
      <div class="chart-grid">
        <section class="card" id="sizes">
          <h2>How big payouts are</h2>
          <p class="note">Count of withdraw transfers in the last 30 days, by size.</p>
          <div id="chart-buckets" class="chart short"></div>
        </section>
        <section class="card" id="cadence">
          <h2>Payouts each day</h2>
          <p class="note">How many withdraw transfers were recorded on each of the last 30 days.</p>
          <div id="chart-counts" class="chart short"></div>
        </section>
      </div>
      <section class="card" id="movement">
        <h2>How USDC moves</h2>
        <p class="note">Last 30 days of observed transfers. Coinbase Prime funds the treasury Safe. Coinbase also sends USDC straight to payout contracts. The Safe sends USDC on to those contracts, directly or through LI.FI; bridge arrivals are not added a second time. Recipients are the outside addresses on withdraw transfers. “Custody (inferred)” is Treasury Safe USDC sent to Coinbase, Coinbase Prime, or the deposit forwarder.</p>
        <div id="chart-sankey" class="chart sankey"></div>
      </section>
    </div>
    <nav class="jumps" aria-label="Details">
      <a href="#wallets">Wallets</a>
      <a href="#moves">Large moves</a>
      <a href="#stats">Payout statistics</a>
      <a href="#method">Methodology</a>
    </nav>
    <details class="fold" id="wallets">
      <summary>Wallets behind the total</summary>
      <div class="body">
        <p class="note">A payout contract is a monitored contract whose outgoing USDC uses the withdraw method. The Treasury Safe is an inference: Coinbase Prime sends it USDC, and it sends USDC on toward the contracts. The Vest pages reviewed for this site do not publish these addresses.</p>
        <div class="scroll"><table>
          <thead><tr><th>Wallet</th><th>Chain</th><th class="num">USDC</th><th class="num">24h</th><th>Attribution</th><th></th></tr></thead>
          <tbody>
            ${(latest.wallets || []).map((w) => `<tr>
              <td>${esc(plainName(w))}${w.stale ? " <span class='muted'>(stale)</span>" : ""}<div class="mono muted">${esc(short(w.address))}</div></td>
              <td>${esc(w.chain)}</td>
              <td class="num">${w.usdc === null || w.usdc === undefined ? "—" : usd.format(w.usdc)}</td>
              <td class="num">${delta(w.change_24h)}</td>
              <td>${badge(w.attribution)}</td>
              <td><a href="${esc(w.explorer)}" rel="noopener">Explorer</a></td>
            </tr>`).join("")}
          </tbody>
        </table></div>
      </div>
    </details>
    <details class="fold" id="moves">
      <summary>Large moves, $10,000 and up</summary>
      <div class="body">
        <p class="note">USDC in or out of a monitored wallet over the last 30 days of stored history. A row marked moved to custody (inferred) is a Treasury Safe transfer to Coinbase, Coinbase Prime, or the deposit forwarder. It is not a payout.</p>
        <div class="scroll"><table>
          <thead><tr><th>Time (UTC)</th><th>Wallet</th><th>Direction</th><th class="num">USDC</th><th>Counterparty</th><th>Tx</th></tr></thead>
          <tbody>
            ${(flows.large_moves || []).map((r) => `<tr>
              <td>${esc(fmtTime(r.t, "UTC"))}</td>
              <td>${esc(r.chain)} · ${esc(plainName({ id: r.wallet_id, role: r.wallet_role }))}</td>
              <td>${esc(r.direction === "in" ? "In" : r.direction === "out" ? "Out" : r.direction)}</td>
              <td class="num">${usd.format(r.amount)}</td>
              <td>${esc(r.counterparty_label || short(r.counterparty))}${r.classification ? `<div>${badge("inferred")} ${esc(r.classification)}</div>` : ""}</td>
              <td><a href="${esc(r.tx_url)}" rel="noopener">${esc(short(r.tx))}</a></td>
            </tr>`).join("") || `<tr><td colspan="6" class="muted">None in the stored window.</td></tr>`}
          </tbody>
        </table></div>
      </div>
    </details>
    <details class="fold" id="stats">
      <summary>Payout statistics</summary>
      <div class="body">${payoutTable(flows)}</div>
    </details>
    <details class="fold" id="method">
      <summary>Methodology and sources</summary>
      <div class="body">${methodology(latest, flows)}</div>
    </details>
  `;
  whenChartsReady(() => drawCharts(latest, history, flows));
}

loadJson("data/latest.json")
  .then((latest) => Promise.all([latest, loadJson("data/history.json"), loadJson("data/flows.json")]))
  .then(([latest, history, flows]) => render(latest, history, flows))
  .catch((err) => {
    document.getElementById("app").innerHTML = `<p class="down">The snapshot could not be loaded (${esc(err.message)}).</p>`;
  });
