const QUOTES = [
  {
    title: "Virtual balances",
    source: "Vest Prop Terms of Service",
    url: "https://trade.vestmarkets.com/prop-terms",
    text: "“Account” means a user’s account in the Program and other records, all as utilized by us from time-to-time to record a user’s virtual balances of digital assets and other usage of the Services.",
  },
  {
    title: "No custody of trading balances shown in the Program",
    source: "Vest Prop Terms of Service, section 6.2",
    url: "https://trade.vestmarkets.com/prop-terms",
    text: "Users do not deposit funds for trading purposes. Any balances, metrics, or performance data displayed in the Program or any given Account are for evaluation or reference purposes only and do not represent ownership of assets or trading accounts. At no time does any user control a brokerage or exchange account, have authority to execute trades, or have custody of any funds used in trading. Any performance metrics, balances, or results displayed to you are notional, simulated, or programmatic in nature and do not correspond to any real account held for your benefit.",
  },
  {
    title: "Hedging with Vest’s own capital",
    source: "Vest Prop Terms of Service",
    url: "https://trade.vestmarkets.com/prop-terms",
    text: "“Hedging Transactions” means risk-management transactions undertaken by us or our Affiliates using our own capital or balance sheet assets in order to reduce or manage the market exposure generated by virtual trading activity occurring in the Program.",
  },
  {
    title: "Evaluation phase uses simulated capital",
    source: "Vest docs, Vest Capital overview",
    url: "https://docs.vestmarkets.com/vest-capital/overview",
    text: "With Evaluation — The traditional prop path. Purchase an account, trade simulated capital in the Evaluation Phase, and configure your risk and reward; Profit Target, Daily Loss Limit, and profit split. Hit your goal to go Live.",
  },
  {
    title: "Live Funded Account, as described by Vest",
    source: "Vest docs, Vest Capital overview",
    url: "https://docs.vestmarkets.com/vest-capital/overview",
    text: "Real Vest capital. Not simulated, actual platform capital backing your positions.",
  },
  {
    title: "Claim Profit",
    source: "Vest docs, Claiming Profit",
    url: "https://docs.vestmarkets.com/vest-capital/claiming-profit",
    text: "Claim Profit moves profit from a Live Funded Account to your Primary Account. It’s the first of two steps if you want to move funds all the way out to an external wallet.",
  },
  {
    title: "Claim Profit is not a withdrawal",
    source: "Vest docs, Claiming Profit",
    url: "https://docs.vestmarkets.com/vest-capital/claiming-profit",
    text: "Claim Profit is not the same as a Withdrawal. Claim Profit moves funds from a Funded Account to your Primary Account. Withdrawal moves funds from your Primary Account to an external wallet.",
  },
  {
    title: "Withdrawal",
    source: "Vest docs, Withdrawals",
    url: "https://docs.vestmarkets.com/platform/withdrawals",
    text: "Withdrawals move USDC from your Primary Account to an external wallet address.",
  },
  {
    title: "Withdrawal limits",
    source: "Vest docs, Withdrawals",
    url: "https://docs.vestmarkets.com/platform/withdrawals",
    text: "Minimum withdrawal: 1 USDC. $50,000 rolling 24-hour limit. Withdrawals process instantly until your rolling 24-hour total reaches $50,000. Any withdrawal that pushes your rolling total over that amount is subject to a 24-hour processing period.",
  },
  {
    title: "Marketing site",
    source: "vestmarkets.com",
    url: "https://vestmarkets.com",
    text: "Trade on a simulated account. Hit the 10% profit target while respecting risk rules. Get funded and keep 80% of every dollar you make. Withdrawals hit your wallet immediately.",
  },
  {
    title: "Card payments",
    source: "Vest Privacy Policy",
    url: "https://docs.vestmarkets.com/resources/terms-and-privacy-policies/privacy-policy",
    text: "When you pay through Stripe Checkout, Stripe processes your payment details. If you opt to save a method, Stripe stores it for later Vest Checkout sessions. We may receive Stripe identifiers and limited card details, such as card brand, last four digits, and expiry, but not the full card number or CVC/CVV.",
  },
];

const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 });
const num = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });

function esc(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

function fmtTime(iso, zone) {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return esc(iso);
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: zone,
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  }).format(d);
}

function delta(v) {
  if (v === null || v === undefined || Number.isNaN(v)) return "<span class='muted'>—</span>";
  const cls = v > 0 ? "up" : v < 0 ? "down" : "";
  const sign = v > 0 ? "+" : "";
  return `<span class="${cls}">${sign}${usd.format(v)}</span>`;
}

function short(addr) {
  if (!addr) return "—";
  return addr.slice(0, 6) + "…" + addr.slice(-4);
}

function badge(attr) {
  const cls = attr === "inferred" ? "inferred" : attr === "contract source" ? "source" : "";
  return `<span class="badge ${cls}">${esc(attr || "—")}</span>`;
}

async function loadJson(path) {
  const res = await fetch(path + "?t=" + Date.now(), { cache: "no-store" });
  if (!res.ok) throw new Error(path + " " + res.status);
  return res.json();
}

function coreSeries(history) {
  const keys = history.keys || [];
  const points = [];
  const daily = history.daily || {};
  const firstSnap = (history.points || [])[0]?.[0];
  const days = new Set();
  keys.forEach((k) => (daily[k] || []).forEach((row) => days.add(row[0])));
  [...days].sort().forEach((day) => {
    const t = day + "T00:00:00Z";
    if (firstSnap && t >= firstSnap) return;
    const vals = keys.map((k) => {
      const hit = (daily[k] || []).find((row) => row[0] === day);
      return hit ? hit[1] : null;
    });
    if (vals.every((v) => v !== null && v !== undefined)) {
      points.push({ t, y: vals.reduce((s, v) => s + v, 0), src: "reconstructed" });
    }
  });
  (history.points || []).forEach((row) => {
    const vals = row.slice(1);
    if (vals.length && vals.every((v) => v !== null && v !== undefined)) {
      points.push({ t: row[0], y: vals.reduce((s, v) => s + v, 0), src: "snapshot" });
    }
  });
  const seen = new Set();
  return points.filter((p) => {
    if (seen.has(p.t)) return false;
    seen.add(p.t);
    return true;
  }).sort((a, b) => a.t.localeCompare(b.t));
}

function flowDiagram(windowData) {
  const a = windowData?.amounts || {};
  const box = (title, sub) => `<div class="node"><strong>${esc(title)}</strong><span class="muted">${esc(sub || "")}</span></div>`;
  const arrow = (amount, note) => `<div class="arrow">${esc(note || "")}<b>${usd.format(amount || 0)}</b></div>`;
  return `
    <div class="flow">
      ${box("Coinbase Prime 1", "Ethereum USDC in")}
      ${arrow(a.coinbase_prime_to_safe, "to Safe")}
      ${box("Treasury Safe", "inferred attribution")}
      ${arrow(a.safe_to_lifi, "to LI.FI")}
      ${box("LI.FI diamond", "LiFiDiamond")}
    </div>
    <div class="flow">
      ${box("Coinbase hot wallet", "direct")}
      ${arrow(a.coinbase_hot_to_contract, "to Base contract")}
      ${box("Base contract", "current payout/deposit")}
      ${arrow(a.safe_to_contract, "Safe direct to contracts")}
      ${box("Contracts", "all monitored chains")}
    </div>
    <p class="note">Inferred LI.FI completions at contracts, matched by amount and time: <strong>${usd.format(a.inferred_lifi_to_contract || 0)}</strong>. Bridge-labeled arrivals (mint, LI.FI, TokenMinter, or TokenMessenger as the token sender): <strong>${usd.format(a.bridge_to_contract || 0)}</strong>. The inferred matches are labeled as inferences in the table.</p>`;
}

function render(latest, history, flows) {
  const t = latest.totals || {};
  const when = latest.generated_at;
  const series = coreSeries(history);
  const cov = flows.coverage || {};
  const incomplete = Object.entries(cov).filter(([, m]) => m && m.reached_cutoff === false && !m.skipped);
  const app = document.getElementById("app");
  app.innerHTML = `
    <section class="card" id="headline">
      <div class="row-between">
        <div>
          <h2>On-chain USDC in monitored wallets</h2>
          <p class="note">Sum of USDC balances read from the wallets in the table below. This is not a figure published by Vest, and it is not a count of virtual or funded-account balances described in Vest’s terms.</p>
        </div>
      </div>
      <div class="cards">
        <div class="card stat"><div class="label">Total</div><div class="value">${usd.format(t.usdc || 0)}</div><div class="sub">${t.partial ? "Partial — at least one read failed and an older balance was kept" : "All listed wallets read this run"}</div></div>
        <div class="card stat"><div class="label">Change, 24h</div><div class="value">${delta(t.change_24h)}</div><div class="sub">Core wallets with a prior point</div></div>
        <div class="card stat"><div class="label">Change, 7d</div><div class="value">${delta(t.change_7d)}</div><div class="sub">Shown when every core wallet has a point that far back</div></div>
        <div class="card stat"><div class="label">Last updated</div><div class="value" style="font-size:1rem">${esc(fmtTime(when, "UTC"))} UTC</div><div class="sub">${esc(fmtTime(when, "Europe/Madrid"))} Europe/Madrid</div></div>
      </div>
      ${latest.errors?.length ? `<p class="note">Read warnings this run: ${latest.errors.length}. Previous balances are kept when a new read fails.</p>` : ""}
    </section>

    <section class="card" id="liquidity">
      <h2>Total on-chain liquidity over time</h2>
      <p class="note">Line is the sum of the seven seed wallets (Treasury Safe on Ethereum, Second Safe, Base contract, Arbitrum contract, Ethereum deposit contract, older Arbitrum contract, older BSC contract) at times when every one of those balances is present. Older points marked reconstructed are daily balances derived from the current balance minus later USDC transfers. Snapshot points come from <span class="mono">data/seed-history.csv</span> and this job. A point is omitted when any of the seven values is missing.</p>
      <div class="chart-box"><canvas id="liq"></canvas></div>
    </section>

    <section class="card" id="wallets">
      <h2>Wallets</h2>
      <div class="scroll"><table>
        <thead><tr>
          <th>Chain</th><th>Role</th><th class="num">USDC</th><th class="num">24h</th><th>Attribution</th><th>Explorer</th>
        </tr></thead>
        <tbody>
          ${(latest.wallets || []).map((w) => `<tr>
            <td>${esc(w.chain)}</td>
            <td>${esc(w.role)}<div class="mono muted">${esc(short(w.address))}${w.stale ? " · stale" : ""}</div></td>
            <td class="num">${w.usdc === null || w.usdc === undefined ? "—" : usd.format(w.usdc)}</td>
            <td class="num">${delta(w.change_24h)}</td>
            <td>${badge(w.attribution)}</td>
            <td><a href="${esc(w.explorer)}" rel="noopener">view</a></td>
          </tr>`).join("")}
        </tbody>
      </table></div>
      ${(latest.checked_zero_usdc || []).length ? `<p class="note">Checked and holding 0 of the configured USDC token this run, so omitted from the total: ${latest.checked_zero_usdc.map((w) => esc(w.chain + " " + short(w.address))).join(", ")}.</p>` : ""}
    </section>

    <section class="card" id="flows">
      <div class="row-between">
        <h2>Top-up flows</h2>
        <div class="tabs" id="flow-tabs">
          <button data-d="7" class="active">7 days</button>
          <button data-d="30">30 days</button>
        </div>
      </div>
      <p class="note">Observed USDC transfers: Coinbase Prime 1 into the Treasury Safe, the Safe into the LI.FI diamond, the Safe directly into contracts, and the Coinbase hot wallet into the Base contract. A contract inflow is an inferred LI.FI completion only when its amount is within 3% of a Safe → LI.FI transfer and it lands within 6 hours.</p>
      <div id="flow-diagram">${flowDiagram(flows.windows?.["7"])}</div>
      <h3>Top-ups, last 30 days</h3>
      <div class="scroll"><table>
        <thead><tr><th>Time (UTC)</th><th>Kind</th><th class="num">USDC</th><th>Path</th><th>Tx</th></tr></thead>
        <tbody>
          ${(flows.topups || []).map((r) => `<tr>
            <td>${esc(fmtTime(r.t, "UTC"))}</td>
            <td>${r.inferred ? badge("inferred") : badge("observed")} <span class="muted">${esc(r.kind)}</span></td>
            <td class="num">${usd.format(r.amount)}</td>
            <td>${esc(r.counterparty_label || short(r.counterparty))} · ${esc(r.chain)} ${esc(r.wallet_role)}</td>
            <td><a href="${esc(r.tx_url)}" rel="noopener">${esc(short(r.tx))}</a></td>
          </tr>`).join("") || `<tr><td colspan="5" class="muted">No classified top-ups in the stored window.</td></tr>`}
        </tbody>
      </table></div>
    </section>

    <section class="card" id="payouts">
      <div class="row-between">
        <h2>Payout withdrawals</h2>
        <div class="tabs" id="pay-tabs">
          <button data-d="30" class="active">30 days</button>
          <button data-d="90">90 days</button>
          <button data-d="7">7 days</button>
        </div>
      </div>
      <p class="note">Outbound USDC from current payout/deposit contracts whose transaction method is <span class="mono">withdraw</span> or selector <span class="mono">0xbd69a7ae</span>. BSC rows use the transaction input selector. Coverage depends on how far the transfer scan has reached; see methodology.</p>
      <div id="pay-body"></div>
    </section>

    <section class="card" id="moves">
      <h2>Latest large moves</h2>
      <p class="note">USDC transfers of at least $10,000 in or out of a monitored wallet, over the last 30 days of stored history.</p>
      <div class="scroll"><table>
        <thead><tr><th>Time (UTC)</th><th>Wallet</th><th>Dir</th><th class="num">USDC</th><th>Counterparty</th><th>Tx</th></tr></thead>
        <tbody>
          ${(flows.large_moves || []).map((r) => `<tr>
            <td>${esc(fmtTime(r.t, "UTC"))}</td>
            <td>${esc(r.chain)} · ${esc(r.wallet_role)}</td>
            <td>${esc(r.direction)}</td>
            <td class="num">${usd.format(r.amount)}</td>
            <td>${esc(r.counterparty_label || short(r.counterparty))}</td>
            <td><a href="${esc(r.tx_url)}" rel="noopener">${esc(short(r.tx))}</a></td>
          </tr>`).join("") || `<tr><td colspan="6" class="muted">None in the stored window.</td></tr>`}
        </tbody>
      </table></div>
    </section>

    <section class="card" id="method">
      <h2>Methodology and sources</h2>
      <h3>How the numbers are computed</h3>
      <ul>
        <li>Balances are <span class="mono">eth_call</span> of <span class="mono">balanceOf</span> on the USDC contract, divided by 10^decimals. Ethereum, Base, and Arbitrum USDC use 6 decimals. BSC USDC <span class="mono">0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d</span> uses 18 decimals. Optimism and Polygon also try bridged USDC.e if native USDC is zero.</li>
        <li>RPCs are public endpoints (PublicNode, chain defaults, 1RPC, Ankr), tried in order with retries. A failed read keeps the previous stored balance and marks the wallet stale. It does not write a zero.</li>
        <li>Transfers on Ethereum, Base, Arbitrum, Optimism, and Polygon come from Blockscout v2 <span class="mono">/api/v2/addresses/{address}/token-transfers</span>. BSC Blockscout hosts did not respond for this job, so BSC transfers are <span class="mono">eth_getLogs</span> of the USDC <span class="mono">Transfer</span> event. BSC timestamps inside a log chunk are estimated from the chunk’s end block.</li>
        <li>The headline total adds every wallet listed in the table, including a stale previous balance when a new read fails. 24h and 7d changes use the last stored point at or before that horizon for each core wallet, and sum those deltas. A change is left blank when no earlier point exists inside the allowed gap.</li>
        <li>History in <span class="mono">data/history.json</span> is append-only. The seed file is hourly snapshots from 2026-10-02 21:35 Europe/Madrid (CEST, UTC+2). New points are appended when a balance changes or at least 55 minutes after the previous point. <span class="mono">NA</span> in the seed is a failed read and is stored as null, not zero.</li>
        <li>Daily backfill, when the transfer scan reached 90 days and the balance read succeeded, is the current balance minus later USDC transfers. It stops where an earlier day would imply a negative balance. A transfer between two monitored wallets is copied to the other wallet when the explorer returned only one side.</li>
        <li>Withdrawal stats count only <span class="mono">withdraw</span> / <span class="mono">0xbd69a7ae</span> outs. Median is the middle value, or the mean of the two middle values when the count is even.</li>
      </ul>
      ${incomplete.length ? `<p class="note">Transfer history has not yet reached the 90-day cutoff for: ${incomplete.map(([id]) => esc(id)).join(", ")}. Those stats cover the transfers stored so far. Later scheduled runs continue the backfill.</p>` : `<p class="note">Transfer scans that report reached_cutoff include transfers back to the lookback window.</p>`}
      <p class="note">Machine-readable files: <a href="data/latest.json">data/latest.json</a> (totals, per-wallet balances, <span class="mono">transfers_since_last_run</span>), <a href="data/history.json">data/history.json</a>, <a href="data/flows.json">data/flows.json</a>. Raw: <span class="mono">https://raw.githubusercontent.com/diatle-glitch/vest-watch/main/data/latest.json</span></p>

      <h3>Addresses</h3>
      <div class="scroll"><table>
        <thead><tr><th>Role</th><th>Chain</th><th>Address</th><th>Attribution</th><th>Source note</th></tr></thead>
        <tbody>
          ${(latest.wallets || []).map((w) => `<tr>
            <td>${esc(w.role)}</td><td>${esc(w.chain)}</td>
            <td class="mono"><a href="${esc(w.explorer)}">${esc(w.address)}</a></td>
            <td>${badge(w.attribution)}</td>
            <td>${esc(w.note)}</td>
          </tr>`).join("")}
          ${(flows.counterparties || []).map((c) => `<tr>
            <td>${esc(c.label)}</td><td></td>
            <td class="mono">${esc(c.address || "—")}</td>
            <td>${badge("reference")}</td>
            <td>${esc(c.basis)}</td>
          </tr>`).join("")}
        </tbody>
      </table></div>
      <p class="note">USDC contracts: Ethereum <span class="mono">0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48</span>, Base <span class="mono">0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913</span>, Arbitrum <span class="mono">0xaf88d065e77c8cC2239327C5EDb3A432268e5831</span>, BSC <span class="mono">0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d</span> (18 decimals). Optimism native <span class="mono">0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85</span>, Polygon native <span class="mono">0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359</span>.</p>

      <h3>Withdrawals on the SrcBridge contracts</h3>
      <p>The Ethereum address <span class="mono">0xE80F92077131b9890599E418AE323de71cE1C35a</span> is a TransparentUpgradeableProxy. Blockscout lists its implementation as <a href="https://eth.blockscout.com/address/0xEcD91C77B98d507E3C20Bac86D2541ECbDc881E3">0xEcD91C77B98d507E3C20Bac86D2541ECbDc881E3</a>, verified source name SrcBridge. That source contains <span class="mono">string public constant NAME = "VestRouterV2"</span> and <span class="mono">bytes32 public constant BRIDGE_OPERATOR_ROLE = keccak256("BRIDGE_OPERATOR_ROLE")</span>.</p>
      <p>The verified <span class="mono">withdraw</span> function calls <span class="mono">_withdraw</span>. That function requires the caller, or an address recovered from <span class="mono">validatorSignature</span>, to have <span class="mono">BRIDGE_OPERATOR_ROLE</span>. It also checks chain id, a supported token, a replay mapping <span class="mono">completedTransactions</span>, and a request signature when the account is not <span class="mono">msg.sender</span>. The parameter named <span class="mono">signatureProof</span> is passed to a signer-delegation check. The verified source has no balance variable and no Merkle or state-root check of an off-chain account. Source reviewed from Blockscout on 2026-10-04.</p>
      <p>Live <span class="mono">hasRole</span> results from this run:</p>
      <ul>
        ${((flows.onchain || {}).checks || []).map((c) => `<li>${esc(c.chain)} ${esc(short(c.address))}: ${c.error ? "read failed (" + esc(c.error) + ")" : (c.has_bridge_operator_role ? "operator has BRIDGE_OPERATOR_ROLE" : "operator does not have BRIDGE_OPERATOR_ROLE on this call")}</li>`).join("")}
      </ul>
      <p class="note"><span class="mono">router()</span> on the Ethereum proxy returned <span class="mono">${esc(flows.onchain?.router?.address || "—")}</span>.</p>

      <h3>Evaluation fees and the legacy zkSync router</h3>
      <p>Vest’s privacy policy says purchases are processed through Stripe Checkout (quote below). Those card payments are off-chain. They are not part of the USDC totals on this page.</p>
      <p>${zksyncBlurb(flows.zksync_router)}</p>

      <h3>Vest’s published terms</h3>
      <p class="note">Quotes below are copied from the listed pages. Pages were fetched on 2026-10-04. The docs dump used while building this page is Vest’s <span class="mono">llms-full</span> export.</p>
      ${QUOTES.map((q) => `<h3>${esc(q.title)}</h3><blockquote><p>${esc(q.text)}</p></blockquote><p class="note"><a href="${esc(q.url)}">${esc(q.source)}</a></p>`).join("")}
    </section>
  `;

  drawChart(series);
  wireFlows(flows);
  wirePayouts(flows);
}

function zksyncBlurb(z) {
  if (!z || z.error && !z.tx) return "The zkSync router check did not return a transaction this run.";
  const stale = z.stale ? " This copy was kept from the previous run because the explorer request failed." : "";
  return `The address returned by <span class="mono">router()</span> is <span class="mono">${esc(z.address)}</span>. The newest transaction on page 1 of the zkSync Era block explorer API (newest first) is <a href="${esc(z.explorer)}">${esc(z.tx)}</a>, received at ${esc(fmtTime(z.received_at, "UTC"))} UTC (${esc(fmtTime(z.received_at, "Europe/Madrid"))} Europe/Madrid), status ${esc(z.status || "—")}. Source: ${esc(z.source || "")}.${esc(stale)}`;
}

function drawChart(series) {
  const canvas = document.getElementById("liq");
  if (!canvas) return;
  if (!series.length) {
    canvas.parentElement.insertAdjacentHTML("beforeend", "<p class='note'>No complete total points yet.</p>");
    return;
  }
  if (!window.Chart) {
    const script = document.createElement("script");
    script.src = "https://cdn.jsdelivr.net/npm/chart.js@4.4.6/dist/chart.umd.min.js";
    script.onload = () => drawChart(series);
    script.onerror = () => {
      canvas.parentElement.insertAdjacentHTML("beforeend", "<p class='note'>The chart library did not load. The tables below still use the JSON snapshot.</p>");
    };
    document.head.appendChild(script);
    return;
  }
  const recon = series.some((p) => p.src === "reconstructed");
  new Chart(canvas, {
    type: "line",
    data: {
      datasets: [
        {
          label: recon ? "Total (snapshots and reconstructed days)" : "Total (snapshots)",
          data: series.map((p) => ({ x: Date.parse(p.t), y: p.y })),
          borderColor: "#8fbfa8",
          backgroundColor: "rgba(143,191,168,0.15)",
          pointRadius: 0,
          borderWidth: 2,
          tension: 0.15,
          fill: true,
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: { legend: { labels: { color: "#e7edf4" } } },
      scales: {
        x: {
          type: "linear",
          ticks: {
            color: "#9aa6b4",
            maxTicksLimit: 6,
            callback: (v) => new Date(v).toISOString().slice(0, 16).replace("T", " "),
          },
          grid: { color: "#2d3846" },
        },
        y: {
          ticks: { color: "#9aa6b4", callback: (v) => num.format(v) },
          grid: { color: "#2d3846" },
        },
      },
    },
  });
}

function wireFlows(flows) {
  const tabs = document.getElementById("flow-tabs");
  const box = document.getElementById("flow-diagram");
  if (!tabs) return;
  tabs.addEventListener("click", (ev) => {
    const btn = ev.target.closest("button");
    if (!btn) return;
    tabs.querySelectorAll("button").forEach((b) => b.classList.toggle("active", b === btn));
    box.innerHTML = flowDiagram(flows.windows?.[btn.dataset.d]);
  });
}

function wirePayouts(flows) {
  const body = document.getElementById("pay-body");
  const tabs = document.getElementById("pay-tabs");
  const draw = (days) => {
    const entries = Object.entries(flows.withdrawals || {});
    if (!entries.length) {
      body.innerHTML = "<p class='note'>No withdrawal aggregates stored yet.</p>";
      return;
    }
    body.innerHTML = `<div class="scroll"><table>
      <thead><tr><th>Contract</th><th class="num">Count</th><th class="num">Volume</th><th class="num">Median</th><th class="num">Max</th><th class="num">Recipients</th></tr></thead>
      <tbody>${entries.map(([id, row]) => {
        const w = row.windows?.[days] || {};
        return `<tr>
          <td>${esc(id)}</td>
          <td class="num">${num.format(w.count || 0)}</td>
          <td class="num">${usd.format(w.volume || 0)}</td>
          <td class="num">${w.median === null || w.median === undefined ? "—" : usd.format(w.median)}</td>
          <td class="num">${w.max === null || w.max === undefined ? "—" : usd.format(w.max)}</td>
          <td class="num">${num.format(w.unique_recipients || 0)}</td>
        </tr>`;
      }).join("")}</tbody></table></div>
      ${entries.map(([id, row]) => {
        const daily = row.windows?.[days]?.daily || [];
        if (!daily.length) return "";
        const max = Math.max(...daily.map((d) => d.volume), 1);
        return `<h3>${esc(id)} daily volume</h3><div class="scroll"><table><tbody>${daily.map((d) => `<tr><td>${esc(d.date)}</td><td class="num">${d.count}</td><td class="num">${usd.format(d.volume)}</td><td><span style="display:inline-block;height:8px;background:#8fbfa8;width:${Math.max(2, (d.volume / max) * 140)}px"></span></td></tr>`).join("")}</tbody></table></div>`;
      }).join("")}`;
  };
  draw("30");
  tabs.addEventListener("click", (ev) => {
    const btn = ev.target.closest("button");
    if (!btn) return;
    tabs.querySelectorAll("button").forEach((b) => b.classList.toggle("active", b === btn));
    draw(btn.dataset.d);
  });
}

loadJson("data/latest.json")
  .then((latest) => Promise.all([latest, loadJson("data/history.json"), loadJson("data/flows.json")]))
  .then(([latest, history, flows]) => render(latest, history, flows))
  .catch((err) => {
    document.getElementById("app").innerHTML = `<section class="card"><p class="error">Could not load data files. ${esc(err.message)}</p></section>`;
  });
